[project]
name = "scripts"
version = "0.1.0"
description = ""
authors = [
    {name = "juchiLee@proton.me",email = "juchiLee@proton.me"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "selenium-driverless (>=1.9.4,<2.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
