[project]
name = "api-contracts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openapi-generator-cli>=7.17.0",
    "setuptools>=80.9.0",
]
